### ISSUE TITLE
Selecting topic

### ISSUE THREAD

**Issue by Pondae** [SE-senior-project/Project#1]
1.Railway tracking and arrival time prediction system
2.Travel planning
3.Search jobs

After we talked with Aj. Kong, we got many ideas and we found the problem of each idea:
- topics are not good enough to make project
- topic's scale too big to complete within 4 months.
- we have a lot of competitors and then we can use Google to search for something better and easier than using our topics.
- topics are very out, people may not use it.

Aj. Kong told us that we can think about our parent business. Boom! we got a lot of idea!!!

Ideas that we got:
1.Valuation systems: 
- we got the project requirements and then we did a basic valuation and we got a framework that we already calculate the valuation and what stuff we buy.
- create checklist to inspect at the work site whether we have problems or not: check the checklist and note step by step whether we should solve the problem or not.

2.Collect requirement: we only make a checklist to remind us of what we need to check.

**Comment by oat431** [comment]
What are you doing?

**Comment by PasakonPJ** [comment]
> What are you doing?

Is not ur business ah

**Comment by Pondae** [comment]
The idea that we choose is: Valuation systems
