### ISSUE TITLE
Requirement

### ISSUE THREAD

**Issue by Pondae** [SE-senior-project/Project#2]
Ask a question, normally, how they measure the work.
**Requirement docs:** https://docs.google.com/document/d/1QwJfOZavt0-Tjq2yE2Gn47yk6aXQnorX8MV2trKFSoQ/edit?usp=sharing

**Comment by PasakonPJ** [comment]
https://docs.google.com/document/d/1BsIgUWp7g3c_J5dPjz4Y7dRx1BeF0ySk80oHzMhXoC0/edit?usp=sharing

**Comment by Pondae** [comment]
Requirement docs: https://docs.google.com/document/d/1QwJfOZavt0-Tjq2yE2Gn47yk6aXQnorX8MV2trKFSoQ/edit?usp=sharing

**Comment by Pondae** [comment]
Requirement II docs: https://docs.google.com/document/d/1dmNcgxssNcP-IUd33PikoFOZFv8DMjqURJO5CAESAXI/edit?usp=sharing
